import { Guesthouse, Region, VibeTag } from "@/types/guesthouse";

export const MOCK_GUESTHOUSES: Guesthouse[] = [
  {
    id: "1",
    name: "썬셋 게스트하우스",
    region: "제주 애월읍",
    price: 18000,
    rating: 4.92,
    reviewCount: 128,
    tags: ["사교적", "혼행자 친화"],
    types: ["도미토리", "개인실"],
    spaces: ["🍳", "🛋️", "🌇"],
    isNew: true,
    emoji: "🌊",
  },
  {
    id: "2",
    name: "경주 한옥 스테이",
    region: "경북 경주시",
    price: 32000,
    rating: 4.87,
    reviewCount: 84,
    tags: ["조용한 편", "한달살기"],
    types: ["개인실"],
    spaces: ["🍳", "🚲"],
    isNew: false,
    emoji: "🏯",
  },
  {
    id: "3",
    name: "파도소리 호스텔",
    region: "부산 해운대구",
    price: 22000,
    rating: 4.78,
    reviewCount: 203,
    tags: ["파티 분위기", "외국인 많음"],
    types: ["도미토리"],
    spaces: ["🛋️", "🌇", "🔥"],
    isNew: false,
    emoji: "🎨",
  },
  {
    id: "4",
    name: "전주 한옥마을 GH",
    region: "전북 전주시",
    price: 25000,
    rating: 4.95,
    reviewCount: 67,
    tags: ["조용한 편", "혼행자 친화"],
    types: ["도미토리", "개인실"],
    spaces: ["🍳", "🚲"],
    isNew: true,
    emoji: "🌸",
  },
  {
    id: "5",
    name: "강릉 바다 호스텔",
    region: "강원 강릉시",
    price: 19000,
    rating: 4.83,
    reviewCount: 156,
    tags: ["사교적", "외국인 많음"],
    types: ["도미토리"],
    spaces: ["🛋️", "🌇", "🍳"],
    isNew: false,
    emoji: "🏔️",
  },
  {
    id: "6",
    name: "여수 낭만 게스트",
    region: "전남 여수시",
    price: 28000,
    rating: 4.91,
    reviewCount: 42,
    tags: ["한달살기", "조용한 편"],
    types: ["개인실"],
    spaces: ["🍳", "🔥", "🚲"],
    isNew: true,
    emoji: "🛖",
  },
  {
    id: "7",
    name: "속초 청춘 호스텔",
    region: "강원 속초시",
    price: 17000,
    rating: 4.8,
    reviewCount: 91,
    tags: ["사교적", "혼행자 친화"],
    types: ["도미토리"],
    spaces: ["🛋️", "🍳"],
    isNew: false,
    emoji: "🌿",
  },
  {
    id: "8",
    name: "통영 바다뷰 GH",
    region: "경남 통영시",
    price: 21000,
    rating: 4.88,
    reviewCount: 33,
    tags: ["조용한 편", "한달살기"],
    types: ["도미토리", "개인실"],
    spaces: ["🌇", "🍳", "🚲"],
    isNew: true,
    emoji: "⛵",
  },
];

export const REGIONS: Region[] = [
  { name: "제주도", count: 142, emoji: "🌊" },
  { name: "경주", count: 58, emoji: "🏯" },
  { name: "부산", count: 96, emoji: "🎨" },
  { name: "전주", count: 44, emoji: "🌸" },
  { name: "강릉", count: 67, emoji: "🏔️" },
  { name: "여수", count: 38, emoji: "🛖" },
  { name: "속초", count: 29, emoji: "🌿" },
  { name: "통영", count: 21, emoji: "⛵" },
];

export const VIBE_TAGS: VibeTag[] = [
  { label: "전체", emoji: "🌿" },
  { label: "조용한 편", emoji: "🤫" },
  { label: "사교적", emoji: "🤝" },
  { label: "혼행자 친화", emoji: "🎒" },
  { label: "파티 분위기", emoji: "🎉" },
  { label: "한달살기", emoji: "📅" },
  { label: "외국인 많음", emoji: "🌍" },
  { label: "바다 근처", emoji: "🌊" },
  { label: "산·자연", emoji: "🏔️" },
];
